version: "3.8"
services:
    botwhatsapp:
        container_name: botwhatsapp
        build:
            context: ./
        environment:
          - PORT=3001
        ports:
            - "3001:3001"
        depends_on:
            - db
            - phpmyadmin
        
    db:
        image: mysql
        container_name: botwhatsapp-mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: "botwhatsapp"
            MYSQL_PASSWORD: "lion"
            MYSQL_ROOT_PASSWORD: "lion"
        ports:
            - "3306:3306"
        volumes:
            - mysql_data:/var/lib/mysql
        networks:
            - lion
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: botwhatsapp-phpmyadmin
        restart: unless-stopped
        links:
            - db:db
        ports:
            - 8080:80
        environment:
            MYSQL_USER: "root"
            MYSQL_PASSWORD: "lion"
            MYSQL_ROOT_PASSWORD: "lion"
        networks:
            - lion
volumes:
    mysql_data:
networks:
    lion:
        driver: bridge
